openapi: 3.0.1
info:
  title: Cognitive Cache API
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/cognitive_cache
  - url: https://api.pre.dvn.com/cognitive_cache
  - url: https://ext.api.pre.dvn.com/cognitive_cache
paths:
  /search:
    get:
      tags:
        - Documents
      summary: Document Search
      description: Search the document store for documents that match the search text. The search can be filtered by category and the number of results can be limited.
      operationId: DocumentSearch
      parameters:
        - name: search
          in: query
          description: The search query
          required: true
          schema:
            title: Search
            minLength: 1
            type: string
            description: The search query
        - name: category
          in: query
          description: The category filter
          schema:
            title: Category
            minLength: 1
            type: string
            description: The category filter
        - name: top
          in: query
          description: The number of search results to retrieve
          schema:
            title: Top
            type: integer
            description: The number of search results to retrieve
            default: 3
        - name: hybrid_search
          in: query
          description: Flag to use hybrid search. A value of false will perform a pure vector search.
          schema:
            title: Hybrid Search
            type: boolean
            description: Flag to use hybrid search. A value of false will perform a pure vector search.
            default: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Document Search Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentSearchResult'
              example:
                - document_chunk:
                    chunk_id: string
                    document_id: string
                    chunk_index: 0
                    title: string
                    content: string
                    category: string
                    url: string
                    owner: string
                    created: string
                    last_modified: string
                  score: 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/documents/{document_id}':
    get:
      tags:
        - Documents
      summary: Get Document Chunks
      description: Retrieves chunks of a document based on the document id provided in the path.
      operationId: GetDocumentChunks
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Document Chunks Documents  Document Id  Get
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                - chunk_id: string
                  document_id: string
                  chunk_index: 0
                  title: string
                  content: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    delete:
      tags:
        - Documents
      summary: Delete Document
      description: Delete a document based on the document id provided in the path.
      operationId: DeleteDocument
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/documents/{document_id}/search':
    get:
      tags:
        - Documents
      summary: Document Search By Id
      description: Search a specific document by id for text
      operationId: DocumentSearchById
      parameters:
        - name: document_id
          in: path
          required: true
          schema:
            type: string
        - name: search
          in: query
          required: true
          schema:
            type: string
        - name: category
          in: query
          description: The category filter
          schema:
            title: Category
            minLength: 1
            type: string
            description: The category filter
        - name: top
          in: query
          description: The number of search results to retrieve
          schema:
            title: Top
            type: integer
            description: The number of search results to retrieve
            default: 3
        - name: hybrid_search
          in: query
          description: Flag to use hybrid search. A value of false will perform a pure vector search.
          schema:
            title: Hybrid Search
            type: boolean
            description: Flag to use hybrid search. A value of false will perform a pure vector search.
            default: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Document Search Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentSearchResult'
              example:
                - document_chunk:
                    chunk_id: string
                    document_id: string
                    chunk_index: 0
                    title: string
                    content: string
                    category: string
                    url: string
                    owner: string
                    created: string
                    last_modified: string
                  score: 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /personal_documents:
    get:
      tags:
        - Personal
      summary: Personal Get Documents
      description: Retrieves a list of personal documents.
      operationId: GetPersonalDocuments
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Get Documents Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocument'
              example:
                - document_id: string
                  title: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    post:
      tags:
        - Personal
      summary: Personal Create Document
      description: "Upload a new personal document to the document store. \nThe document will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns the newly created document header."
      operationId: CreatePersonalDocument
      parameters:
        - name: document_id
          in: query
          description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
        - name: title
          in: query
          description: The document title
          required: true
          schema:
            title: Title
            maxLength: 256
            minLength: 1
            type: string
            description: The document title
        - name: category
          in: query
          description: The document category
          required: true
          schema:
            title: Category
            maxLength: 256
            minLength: 1
            type: string
            description: The document category
        - name: source_url
          in: query
          description: The document source url. This will be provided to models to link back to the document source.
          required: true
          schema:
            title: Source Url
            maxLength: 2048
            minLength: 1
            type: string
            description: The document source url. This will be provided to models to link back to the document source.
        - name: owner
          in: query
          description: The document owner
          required: true
          schema:
            title: Owner
            maxLength: 256
            minLength: 1
            type: string
            description: The document owner
      requestBody:
        content:
          multipart/form-data: { }
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/personal_documents/{document_id}':
    delete:
      tags:
        - Personal
      summary: Personal Delete Document
      description: Delete Document
      operationId: DeletePersonalDocument
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    get:
      tags:
        - Personal
      summary: Personal Get Document Chunks
      description: Get Document Chunks
      operationId: GetPersonalDocumentChunks
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Document Chunks Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                - chunk_id: string
                  document_id: string
                  chunk_index: 0
                  title: string
                  content: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /personal_documents/from_text:
    post:
      tags:
        - Personal
      summary: Personal Create From Text
      description: "Upload text as a new personal document to the document store. \nThe text will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns the newly created document header."
      operationId: CreatePersonalDocumentFromText
      parameters:
        - name: document_id
          in: query
          description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
        - name: title
          in: query
          description: The document title
          required: true
          schema:
            title: Title
            maxLength: 256
            minLength: 1
            type: string
            description: The document title
        - name: category
          in: query
          description: The document category
          required: true
          schema:
            title: Category
            maxLength: 256
            minLength: 1
            type: string
            description: The document category
        - name: source_url
          in: query
          description: The document source url. This will be provided to models to link back to the document source.
          required: true
          schema:
            title: Source Url
            maxLength: 2048
            minLength: 1
            type: string
            description: The document source url. This will be provided to models to link back to the document source.
        - name: owner
          in: query
          description: The document owner
          required: true
          schema:
            title: Owner
            maxLength: 256
            minLength: 1
            type: string
            description: The document owner
      requestBody:
        content:
          application/json:
            schema:
              title: Text
              minLength: 1
              type: string
              description: The text to upload as the body of the request
            example: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/personal_documents/{document_id}/chunks/{chunk_id}':
    delete:
      tags:
        - Personal
      summary: Personal Delete Document Chunk
      description: Allows you to delete a chunk from a personal document based on the document id and chunk id provided in the path.
      operationId: DeletePersonalDocumentChunk
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: chunk_id
          in: path
          description: The chunk id to retrieve
          required: true
          schema:
            title: Chunk Id
            maxLength: 256
            minLength: 1
            type: string
            description: The chunk id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    get:
      tags:
        - Personal
      summary: Personal Get Document Chunk
      description: Retrieves a chunk from a personal document based on the document id and chunk id provided in the path.
      operationId: GetPersonalDocumentChunk
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: chunk_id
          in: path
          description: The chunk id to retrieve
          required: true
          schema:
            title: Chunk Id
            maxLength: 256
            minLength: 1
            type: string
            description: The chunk id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                chunk_id: string
                document_id: string
                chunk_index: 0
                title: string
                content: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /personal_documents/search:
    get:
      tags:
        - Personal
      summary: Personal Document Search
      description: Search the document store for personal documents that match the search text. The search can be filtered by category and the number of results can be limited.
      operationId: PersonalDocumentSearch
      parameters:
        - name: search
          in: query
          description: The search query
          required: true
          schema:
            title: Search
            minLength: 1
            type: string
            description: The search query
        - name: category
          in: query
          description: The category filter
          schema:
            title: Category
            minLength: 1
            type: string
            description: The category filter
        - name: top
          in: query
          description: The number of search results to retrieve
          schema:
            title: Top
            type: integer
            description: The number of search results to retrieve
            default: 3
        - name: hybrid_search
          in: query
          description: Flag to use hybrid search. A value of false will perform a pure vector search.
          schema:
            title: Hybrid Search
            type: boolean
            description: Flag to use hybrid search. A value of false will perform a pure vector search.
            default: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Document Search Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentSearchResult'
              example:
                - document_chunk:
                    chunk_id: string
                    document_id: string
                    chunk_index: 0
                    title: string
                    content: string
                    category: string
                    url: string
                    owner: string
                    created: string
                    last_modified: string
                  score: 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /enterprise_documents:
    get:
      tags:
        - Enterprise
      summary: Enterprise Get Documents
      description: Retrieves a list of enterprise documents.
      operationId: GetEnterpriseDocuments
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Get Documents Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocument'
              example:
                - document_id: string
                  title: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    post:
      tags:
        - Enterprise
      summary: Enterprise Create Document
      description: "Upload a new enterprise document to the document store. \nThe document will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns the newly created document header."
      operationId: CreateEnterpriseDocument
      parameters:
        - name: document_id
          in: query
          description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
        - name: title
          in: query
          description: The document title
          required: true
          schema:
            title: Title
            maxLength: 256
            minLength: 1
            type: string
            description: The document title
        - name: category
          in: query
          description: The document category
          required: true
          schema:
            title: Category
            maxLength: 256
            minLength: 1
            type: string
            description: The document category
        - name: source_url
          in: query
          description: The document source url. This will be provided to models to link back to the document source.
          required: true
          schema:
            title: Source Url
            maxLength: 2048
            minLength: 1
            type: string
            description: The document source url. This will be provided to models to link back to the document source.
        - name: owner
          in: query
          description: The document owner
          required: true
          schema:
            title: Owner
            maxLength: 256
            minLength: 1
            type: string
            description: The document owner
      requestBody:
        content:
          multipart/form-data: { }
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/enterprise_documents/{document_id}':
    get:
      tags:
        - Enterprise
      summary: Enterprise Get Document Chunks
      description: Retrieves chunks of an enterprise document based on the document id provided in the path.
      operationId: GetEnterpriseDocumentChunks
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Document Chunks Documents  Document Id  Get
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                - chunk_id: string
                  document_id: string
                  chunk_index: 0
                  title: string
                  content: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    delete:
      tags:
        - Enterprise
      summary: Enterprise Delete Document
      description: Delete an enterprise document based on the document id provided in the path.
      operationId: DeleteEnterpriseDocument
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /enterprise_documents/search:
    get:
      tags:
        - Enterprise
      summary: Enterprise Document Search
      description: search the document store for enterprise documents that match the search text. The search can be filtered by category and the number of results can be limited.
      operationId: EnterpriseDocumentSearch
      parameters:
        - name: search
          in: query
          description: The search query
          required: true
          schema:
            title: Search
            minLength: 1
            type: string
            description: The search query
        - name: category
          in: query
          description: The category filter
          schema:
            title: Category
            minLength: 1
            type: string
            description: The category filter
        - name: top
          in: query
          description: The number of search results to retrieve
          schema:
            title: Top
            type: integer
            description: The number of search results to retrieve
            default: 3
        - name: hybrid_search
          in: query
          description: Flag to use hybrid search. A value of false will perform a pure vector search.
          schema:
            title: Hybrid Search
            type: boolean
            description: Flag to use hybrid search. A value of false will perform a pure vector search.
            default: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Document Search Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentSearchResult'
              example:
                - document_chunk:
                    chunk_id: string
                    document_id: string
                    chunk_index: 0
                    title: string
                    content: string
                    category: string
                    url: string
                    owner: string
                    created: string
                    last_modified: string
                  score: 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/enterprise_documents/{document_id}/chunks/{chunk_id}':
    get:
      tags:
        - Enterprise
      summary: Enterprise Get Document Chunk
      description: Retrieves a chunk from an enterprise document based on the document id and chunk id provided in the path.
      operationId: GetEnterpriseDocumentChunk
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: chunk_id
          in: path
          description: The chunk id to retrieve
          required: true
          schema:
            title: Chunk Id
            maxLength: 256
            minLength: 1
            type: string
            description: The chunk id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                chunk_id: string
                document_id: string
                chunk_index: 0
                title: string
                content: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    delete:
      tags:
        - Enterprise
      summary: Enterprise Delete Document Chunk
      description: Delete a chunk from an enterprise document based on the document id and chunk id provided in the path.
      operationId: DeleteEnterpriseDocumentChunk
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: chunk_id
          in: path
          description: The chunk id to retrieve
          required: true
          schema:
            title: Chunk Id
            maxLength: 256
            minLength: 1
            type: string
            description: The chunk id to retrieve
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /enterprise_documents/from_text:
    post:
      tags:
        - Enterprise
      summary: Enterprise Create From Text
      description: "Upload text as a new enterprise document to the document store. \nThe text will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns the newly created document header."
      operationId: CreateEnterpriseDocumentFromText
      parameters:
        - name: document_id
          in: query
          description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: "The unique ID of the ocument to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id."
        - name: title
          in: query
          description: The document title
          required: true
          schema:
            title: Title
            maxLength: 256
            minLength: 1
            type: string
            description: The document title
        - name: category
          in: query
          description: The document category
          required: true
          schema:
            title: Category
            maxLength: 256
            minLength: 1
            type: string
            description: The document category
        - name: source_url
          in: query
          description: The document source url. This will be provided to models to link back to the document source.
          required: true
          schema:
            title: Source Url
            maxLength: 2048
            minLength: 1
            type: string
            description: The document source url. This will be provided to models to link back to the document source.
        - name: owner
          in: query
          description: The document owner
          required: true
          schema:
            title: Owner
            maxLength: 256
            minLength: 1
            type: string
            description: The document owner
      requestBody:
        content:
          application/json:
            schema:
              title: Text
              minLength: 1
              type: string
              description: The text to upload as the body of the request
            example: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /team_documents:
    get:
      tags:
        - Team
      summary: Team Get Documents
      description: Retrieves a list of team documents.
      operationId: GetTeamDocuments
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Get Documents Response
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocument'
              example:
                - document_id: string
                  title: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/team_documents/{team_id}':
    post:
      tags:
        - Team
      summary: Team Create Document
      description: "Upload a new team document to the document store for a specific team. \nThe document will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns the newly created document header."
      operationId: CreateTeamDocument
      parameters:
        - name: team_id
          in: path
          required: true
          schema:
            type: string
        - name: document_id
          in: query
          required: true
          schema:
            type: string
        - name: title
          in: query
          required: true
          schema:
            type: string
        - name: category
          in: query
          required: true
          schema:
            type: string
        - name: source_url
          in: query
          required: true
          schema:
            type: string
        - name: owner
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data: { }
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
components:
  schemas:
    DVNDocument:
      title: DVNDocument
      required:
        - document_id
        - title
        - category
        - url
        - owner
        - created
        - last_modified
      type: object
      properties:
        document_id:
          title: Document Id
          type: string
        title:
          title: Title
          type: string
        category:
          title: Category
          type: string
        url:
          title: Url
          type: string
        owner:
          title: Owner
          type: string
        created:
          title: Created
          type: string
          format: date-time
        last_modified:
          title: Last Modified
          type: string
          format: date-time
    DVNDocumentChunk:
      title: DVNDocumentChunk
      required:
        - chunk_id
        - document_id
        - chunk_index
        - title
        - content
        - category
        - url
        - owner
        - created
        - last_modified
      type: object
      properties:
        chunk_id:
          title: Chunk Id
          type: string
        document_id:
          title: Document Id
          type: string
        chunk_index:
          title: Chunk Index
          type: integer
        title:
          title: Title
          type: string
        content:
          title: Content
          type: string
        category:
          title: Category
          type: string
        url:
          title: Url
          type: string
        owner:
          title: Owner
          type: string
        created:
          title: Created
          type: string
          format: date-time
        last_modified:
          title: Last Modified
          type: string
          format: date-time
    DVNDocumentSearchResult:
      title: DVNDocumentSearchResult
      required:
        - document_chunk
        - score
      type: object
      properties:
        document_chunk:
          $ref: '#/components/schemas/DVNDocumentChunk'
        score:
          title: Score
          type: number
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    TiktokenRequest:
      title: TiktokenRequest
      required:
        - text
      type: object
      properties:
        text:
          title: Text
          type: string
        encoding:
          title: Encoding
          type: string
          default: cl100k_base
    TiktokenResponse:
      title: TiktokenResponse
      required:
        - token_count
        - tokens
      type: object
      properties:
        token_count:
          title: Token Count
          type: integer
        tokens:
          title: Tokens
          type: array
          items:
            type: integer
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]