openapi: 3.0.1
info:
  title: AI Toolkit API
  version: '1.0'
servers:
  - url: https://apim.pre.dvn.com/aitoolkit
  - url: https://api.pre.dvn.com/aitoolkit
  - url: https://ext.api.pre.dvn.com/aitoolkit
paths:
  /tiktoken/encode:
    post:
      tags:
        - Tiktoken
      summary: Tiktoken Encode
      description: Tiktoken Encode
      operationId: TiktokenEncode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TiktokenRequest'
            example:
              text: string
              encoding: cl100k_base
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TiktokenResponse'
              example:
                token_count: 0
                tokens:
                  - 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /documents:
    get:
      tags:
        - Documents
      summary: Get Documents
      description: Retrieves a list of documents based on the provided security groups.
      operationId: GetDocuments
      parameters:
        - name: security_groups
          in: query
          description: 'The group ids to retrieve documents for. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: 'The group ids to retrieve documents for. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
        - name: category
          in: query
          description: The category filter
          schema:
            title: Category
            minLength: 1
            type: string
            description: The category filter
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Documents Documents Get
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocument'
              example:
                - document_id: string
                  title: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    post:
      tags:
        - Documents
      summary: Document Create
      description: "Upload a new document to the document store. \nThe document will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns a list containing the newly created chunk ids."
      operationId: CreateDocument
      parameters:
        - name: security_groups
          in: query
          description: 'The security group ids that the document belongs to. To pass multiple group ids use the query parameter multiple times, e.g. ?security_groups=g1&security_groups=g2&security_groups=g3'
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: 'The security group ids that the document belongs to. To pass multiple group ids use the query parameter multiple times, e.g. ?security_groups=g1&security_groups=g2&security_groups=g3'
        - name: title
          in: query
          description: The document title
          required: true
          schema:
            title: Title
            maxLength: 256
            minLength: 1
            type: string
            description: The document title
        - name: category
          in: query
          description: The document category
          required: true
          schema:
            title: Category
            maxLength: 256
            minLength: 1
            type: string
            description: The document category
        - name: source_url
          in: query
          description: The document source url. This will be provided to models to link back to the document source.
          required: true
          schema:
            title: Source Url
            maxLength: 2048
            minLength: 1
            type: string
            description: The document source url. This will be provided to models to link back to the document source.
        - name: owner
          in: query
          description: The document owner
          required: true
          schema:
            title: Owner
            maxLength: 256
            minLength: 1
            type: string
            description: The document owner
        - name: document_id
          in: query
          description: "The unique ID of the document to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id. If not provided, a unique id will be created by hashing the file."
          schema:
            title: Document Id
            maxLength: 256
            type: string
            description: "The unique ID of the document to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id. If not provided, a unique id will be created by hashing the file."
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                document:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /documents/search:
    get:
      tags:
        - Documents
      summary: Document Search
      description: Search the document store for documents matching the search text
      operationId: DocumentSearch
      parameters:
        - name: security_groups
          in: query
          description: 'The group ids to include in the document search. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: 'The group ids to include in the document search. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
        - name: search
          in: query
          description: The search query
          required: true
          schema:
            title: Search
            minLength: 1
            type: string
            description: The search query
        - name: category
          in: query
          description: The category filter
          schema:
            title: Category
            minLength: 1
            type: string
            description: The category filter
        - name: top
          in: query
          description: The number of search results to retrieve
          schema:
            title: Top
            type: integer
            description: The number of search results to retrieve
            default: 3
        - name: hybrid_search
          in: query
          description: Flag to use hybrid search. A value of false will perform a pure vector search.
          schema:
            title: Hybrid Search
            type: boolean
            description: Flag to use hybrid search. A value of false will perform a pure vector search.
            default: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Document Search Documents Search Get
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentSearchResult'
              example:
                - document_chunk:
                    chunk_id: string
                    document_id: string
                    chunk_index: 0
                    title: string
                    content: string
                    category: string
                    url: string
                    owner: string
                    created: string
                    last_modified: string
                  score: 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  /documents/from_text:
    post:
      tags:
        - Documents
      summary: Document Create From Text
      description: "Upload text as a new document to the document store. \nThe text will be split into chunks and each chunk will be embedded and indexed for search.\n\nReturns a list containing the newly created chunk ids."
      operationId: CreateDocumentFromText
      parameters:
        - name: security_groups
          in: query
          description: 'The security group ids that the document belongs to. To pass multiple group ids use the query parameter multiple times, e.g. ?security_groups=g1&security_groups=g2&security_groups=g3'
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: 'The security group ids that the document belongs to. To pass multiple group ids use the query parameter multiple times, e.g. ?security_groups=g1&security_groups=g2&security_groups=g3'
        - name: title
          in: query
          description: The document title
          required: true
          schema:
            title: Title
            maxLength: 256
            minLength: 1
            type: string
            description: The document title
        - name: category
          in: query
          description: The document category
          required: true
          schema:
            title: Category
            maxLength: 256
            minLength: 1
            type: string
            description: The document category
        - name: source_url
          in: query
          description: The document source url. This will be provided to models to link back to the document source.
          required: true
          schema:
            title: Source Url
            maxLength: 2048
            minLength: 1
            type: string
            description: The document source url. This will be provided to models to link back to the document source.
        - name: owner
          in: query
          description: The document owner
          required: true
          schema:
            title: Owner
            maxLength: 256
            minLength: 1
            type: string
            description: The document owner
        - name: document_id
          in: query
          description: "The unique ID of the document to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id. If not provided, a unique id will be created by hashing the file."
          schema:
            title: Document Id
            maxLength: 256
            type: string
            description: "The unique ID of the document to be uploaded, for documents from external systems use a system \n            generated unique id so documents so documents can be updated without having to track the DVN document id. If not provided, a unique id will be created by hashing the file."
      requestBody:
        content:
          application/json:
            schema:
              title: Text
              minLength: 1
              type: string
              description: The text to upload as the body of the request
            example: string
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocument'
              example:
                document_id: string
                title: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/documents/{document_id}':
    get:
      tags:
        - Documents
      summary: Get Document Chunks
      description: Get Document Chunks
      operationId: GetDocumentChunks
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: security_groups
          in: query
          description: 'The group ids to include in the search. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: 'The group ids to include in the search. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Document Chunks Documents  Document Id  Get
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                - chunk_id: string
                  document_id: string
                  chunk_index: 0
                  title: string
                  content: string
                  category: string
                  url: string
                  owner: string
                  created: string
                  last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    delete:
      tags:
        - Documents
      summary: Delete Document
      description: Delete Document
      operationId: DeleteDocument
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: security_groups
          in: query
          description: The group ids to include in the document search.
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: The group ids to include in the document search.
      responses:
        '204':
          description: Successful Response
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/documents/{document_id}/search':
    get:
      tags:
        - Documents
      summary: Search Document By Id
      description: Search the document store for documents matching the search text
      operationId: SearchDocumentById
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: security_groups
          in: query
          description: 'The group ids to include in the document search. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: 'The group ids to include in the document search. To pass multiple group ids use the query parameter multiple times, e.g. ?groups=group1&groups=group2&groups=group3'
        - name: search
          in: query
          description: The search query
          required: true
          schema:
            title: Search
            minLength: 1
            type: string
            description: The search query
        - name: top
          in: query
          description: The number of search results to retrieve
          schema:
            title: Top
            type: integer
            description: The number of search results to retrieve
            default: 3
        - name: hybrid_search
          in: query
          description: Flag to use hybrid search. A value of false will perform a pure vector search.
          schema:
            title: Hybrid Search
            type: boolean
            description: Flag to use hybrid search. A value of false will perform a pure vector search.
            default: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Search Document By Id Documents  Document Id  Search Get
                type: array
                items:
                  $ref: '#/components/schemas/DVNDocumentSearchResult'
              example:
                - document_chunk:
                    chunk_id: string
                    document_id: string
                    chunk_index: 0
                    title: string
                    content: string
                    category: string
                    url: string
                    owner: string
                    created: string
                    last_modified: string
                    token_count: 0
                  score: 0
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
  '/documents/{document_id}/chunks/{chunk_id}':
    get:
      tags:
        - Documents
      summary: Get Document Chunk
      description: Get Document Chunk
      operationId: GetDocumentChunk
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: chunk_id
          in: path
          description: The chunk id to retrieve
          required: true
          schema:
            title: Chunk Id
            maxLength: 256
            minLength: 1
            type: string
            description: The chunk id to retrieve
        - name: security_groups
          in: query
          description: The group ids to include in the document search.
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: The group ids to include in the document search.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DVNDocumentChunk'
              example:
                chunk_id: string
                document_id: string
                chunk_index: 0
                title: string
                content: string
                category: string
                url: string
                owner: string
                created: string
                last_modified: string
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
    delete:
      tags:
        - Documents
      summary: Delete Document Chunk
      description: Delete Document Chunk
      operationId: DeleteDocumentChunk
      parameters:
        - name: document_id
          in: path
          description: The document id to retrieve
          required: true
          schema:
            title: Document Id
            maxLength: 256
            minLength: 1
            type: string
            description: The document id to retrieve
        - name: chunk_id
          in: path
          description: The chunk id to retrieve
          required: true
          schema:
            title: Chunk Id
            maxLength: 256
            minLength: 1
            type: string
            description: The chunk id to retrieve
        - name: security_groups
          in: query
          description: The group ids to include in the document search.
          required: true
          schema:
            title: Security Groups
            minLength: 1
            type: array
            items:
              minLength: 1
              type: string
            description: The group ids to include in the document search.
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: { }
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
              example:
                detail:
                  - loc:
                      - { }
                    msg: string
                    type: string
components:
  schemas:
    Body_document_create_documents_post:
      title: Body_document_create_documents_post
      required:
        - document
      type: object
      properties:
        document:
          title: Document
          type: string
          description: The document file to upload as a file in the body of the request
          format: binary
    DVNDocument:
      title: DVNDocument
      required:
        - document_id
        - title
        - category
        - url
        - owner
        - created
        - last_modified
      type: object
      properties:
        document_id:
          title: Document Id
          type: string
        title:
          title: Title
          type: string
        category:
          title: Category
          type: string
        url:
          title: Url
          type: string
        owner:
          title: Owner
          type: string
        created:
          title: Created
          type: string
          format: date-time
        last_modified:
          title: Last Modified
          type: string
          format: date-time
    DVNDocumentChunk:
      title: DVNDocumentChunk
      required:
        - chunk_id
        - document_id
        - chunk_index
        - title
        - content
        - category
        - url
        - owner
        - created
        - last_modified
      type: object
      properties:
        chunk_id:
          title: Chunk Id
          type: string
        document_id:
          title: Document Id
          type: string
        chunk_index:
          title: Chunk Index
          type: integer
        title:
          title: Title
          type: string
        content:
          title: Content
          type: string
        category:
          title: Category
          type: string
        url:
          title: Url
          type: string
        owner:
          title: Owner
          type: string
        created:
          title: Created
          type: string
          format: date-time
        last_modified:
          title: Last Modified
          type: string
          format: date-time
        token_count:
          title: Token Count
          type: integer
    DVNDocumentSearchResult:
      title: DVNDocumentSearchResult
      required:
        - document_chunk
        - score
      type: object
      properties:
        document_chunk:
          $ref: '#/components/schemas/DVNDocumentChunk'
        score:
          title: Score
          type: number
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    TiktokenRequest:
      title: TiktokenRequest
      required:
        - text
      type: object
      properties:
        text:
          title: Text
          type: string
        encoding:
          title: Encoding
          type: string
          default: cl100k_base
    TiktokenResponse:
      title: TiktokenResponse
      required:
        - token_count
        - tokens
      type: object
      properties:
        token_count:
          title: Token Count
          type: integer
        tokens:
          title: Tokens
          type: array
          items:
            type: integer
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]